{
  "listen_host": "127.0.0.1",
  "listen_port": 7070,
  "tunnel_socks5_host": "127.0.0.1",
  "tunnel_socks5_port": 40001,
  "cache_db": "/var/lib/smart-proxy/cache.db",
  "test_timeout": 3.0,
  "test_slow_threshold": 1.5,
  "geo_dir": "/usr/local/x-ui/bin",
  "special_category_url": "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-porn",
  "tunnel_always": [
    "youtube.com",
    "youtu.be",
    "ytimg.com",
    "googlevideo.com",
    "yt3.ggpht.com",
    "telegram.org",
    "t.me",
    "telegram.me",
    "core.telegram.org",
    "instagram.com",
    "cdninstagram.com",
    "facebook.com",
    "fbcdn.net",
    "fb.com",
    "meta.com",
    "twitter.com",
    "x.com",
    "twimg.com",
    "discord.com",
    "discordapp.com",
    "discord.gg",
    "openai.com",
    "chatgpt.com",
    "claude.ai",
    "anthropic.com",
    "gemini.google.com",
    "generativelanguage.googleapis.com",
    "duckduckgo.com",
    "ddg.gg",
    "spotify.com",
    "scdn.co",
    "netflix.com",
    "nflximg.com",
    "github.com",
    "githubusercontent.com",
    "githubassets.com",
    "canva.com",
    "medium.com"
  ],
  "direct_always": [
    "ru",
    "rf",
    "xn--p1ai",
    "gosuslugi.ru",
    "mos.ru",
    "nalog.ru",
    "nalog.gov.ru",
    "sberbank.ru",
    "sber.ru",
    "sbbol.ru",
    "vtb.ru",
    "alfabank.ru",
    "tinkoff.ru",
    "raiffeisen.ru",
    "ozon.ru",
    "wildberries.ru",
    "avito.ru",
    "hh.ru",
    "yandex.ru",
    "yandex.net",
    "ya.ru",
    "vk.com",
    "vk.me",
    "userapi.com",
    "mail.ru",
    "ok.ru",
    "{{BASE_DOMAIN}}",
    "{{NODE_FQDN}}",
    "{{INTERNAL_IPV4}}"
  ],
  "filtered_keyword": "{{FILTERED_KEYWORD}}"
}
